dynamics_translation_noise_std_dev: 0.5 # standard deviation for gaussian noise in translational prediction of particles (float)
dynamics_orientation_noise_std_dev: 0.01 # standard deviation for gaussian noise in rotational prediction of particles (float)
num_particles: 200 # numer of particles (int)
num_beams: 30 # numer of laser beams (int)
update_rate: 2 # rate of prediction and update in Hz (int)
odom_noise: False # incorperates noise in odometry messages used for predicting the particles (bool) 
launch_style: init # initializes particles rnaodmly or close to spawn pose of robot (init,random) (random does not work reliably with small amound of particles)
normalized_commulated_localization_error: 12 # threshold for average error for all particles (float)
variance_increase_for_bad_localization: 2 # variance increase if odometry is used for estaimating pose of robot (float)
