# Map to start the costmap generator with.
init_map_nr: 1

# Log execution times of critical operations.
log_times: True

# Return debugging messages to the terminal.
debug_mode: False

# Parameters necessary for the generation of the global costmap.
global_costmap: {
  robot_diameter: 0.45,
  safety_distance: 0.0, #0.1
  padded_val: 99,
  apply_soft_padding: True,
  decay_distance: 0.2,
  decay_type: exponential # linear, exponential, reciprocal
}

# Parameters necessary for the generation of the local costmap.
local_costmap: {
  length: 3,
  frequency: 10,
  frequency_scan: 40
}
